### ISSUE TITLE
Mariadb not booting after server reboot

### ISSUE THREAD

**Issue by edorgeville** [Kloadut/dokku-md-plugin#16]
Hey guys,
After running a `sudo reboot` it seems like a mariadb container didn't restart properly. I am not able to access it or anything until I manually remove it (see #12), then recreate it and restore the data from a SQL backup.
Here are the logs :

> 140318 20:33:07 mysqld_safe Logging to syslog.
> 140318 20:33:07 mysqld_safe Starting mysqld daemon with databases from /opt/mysql
> 140318 20:47:27 mysqld_safe Number of processes running now: 0
> 140318 20:47:27 mysqld_safe mysqld restarted
> 140318 20:53:13 mysqld_safe Number of processes running now: 0
> 140318 20:53:13 mysqld_safe mysqld restarted
> 140318 20:59:54 mysqld_safe Number of processes running now: 0
> 140318 20:59:54 mysqld_safe mysqld restarted
> 140318 21:00:07 mysqld_safe Number of processes running now: 0
> 140318 21:00:07 mysqld_safe mysqld restarted
> 140318 21:00:12 mysqld_safe Number of processes running now: 0
> 140318 21:00:12 mysqld_safe mysqld restarted
> 140318 21:00:35 mysqld_safe Number of processes running now: 0
> 140318 21:00:35 mysqld_safe mysqld restarted
> 140318 22:53:22 mysqld_safe Logging to syslog.
> 140318 22:53:22 mysqld_safe Starting mysqld daemon with databases from /opt/mysql
> 140318 22:53:23 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended

The reboot happened around 22:50, so only the last 3 lines seems to be useful.

**Comment by codeinabox** [comment]
I am having a similar issue after rebooting the server

       vagrant@dokku:~$ dokku  mariadb:info testdb
       Host: 172.17.42.1
       Port: 49153
       User: 'root'
       Password: 'QMFtsX9avbGb1wRm'
       Database: 'db'

       vagrant@dokku:~$ dokku  mariadb:console testdb
       ERROR 2003 (HY000): Can't connect to MySQL server on '172.17.42.1' (111)

I tried running `docker ps` but I get this error

       FATA[0000] Get http:///var/run/docker.sock/v1.16/containers/json: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?

**Comment by slava-vishnyakov** [comment]
After restart I need to do this to manually relink containers:

``` sh
docker ps -a | grep mariadb | awk {'print "docker start " $1'} | bash
docker ps -a | grep mariadb | sed -r 's/^.*?mariadb\/(.*?):.*?:(.*?)->3306.*/echo \2 > \/home\/dokku\/.mariadb\/port_\1; dokku mariadb:link \1;/' | bash
```

It's a hack, but I don't see a better solution, MariaDB containers are not started and not linked.
