### ISSUE TITLE
mariadb

### ISSUE THREAD

**Issue by bashilbers** [Kloadut/dokku-md-plugin#25]
Sorry for the noobish question, but I can't seem to get it working.. after rebooting my server, `dokku logs app` keeps telling me this:

What am I doing wrong? (I have linked my app container to a dokku:mariadb container)

root@vm1:~# dokku logs app

ERROR: There is a problem with the database
connect ETIMEDOUT, sql: select \* from information_schema.tables where table_schema = ? and table_name = ?, bindings: db,settings

**Comment by fedosov** [comment]
I can't access MariaDB from my app container too.
