### ISSUE TITLE
Dockerfile not found

### ISSUE THREAD

**Issue by will-hart** [Kloadut/dokku-md-plugin#31]
I receive an error when following the installation steps exactly:

```
2014/08/30 11:03:51 no Dockerfile found in /var/lib/dokku/plugins/mariadb/dockerfiles
```

It looks like the submodule is not being checked out. This is fixed by 

```
git clone --recursive https://github.com/Kloadut/dokku-md-plugin mariadb
```

However when I run `dokku plugins-install` (on Ubuntu 14.04) I get this output:

```
Sending build context to Docker daemon 7.168 kB
Sending build context to Docker daemon
2014/08/30 11:06:08 The command [/bin/sh -c apt-get update] returned a non-zero code: 100
```

(I get this same issue with your [Postgresql plugin](https://github.com/Kloadut/dokku-pg-plugin) by the way). After seeing #13, I tried a fresh approach:

```
cd /var/lib/dokku/plugins/
git clone --recursive https://github.com/Kloadut/dokku-md-plugin mariadb
cd mariadb/dockerfiles
git checkout master
dokku plugins-install
```

This worked.

**Comment by scher200** [comment]
+1 thanks, i needed this
