### ISSUE TITLE
MariaDB image not found... 

### ISSUE THREAD

**Issue by remy-actual** [Kloadut/dokku-md-plugin#45]
Fresh install from Digital Ocean Dokku 0.3.18 image on Ubuntu 14.04:
After followed installation instructions for plugin.

```
$ dokku mariadb:create app
MariaDB image not found... Did you run 'dokku plugins-install' 
```

`dokku plugins-install` has been run with and without sudo, as well as `dokku plugins-update`.  

`dokku plugins` returns mariadb as an active dokku plugin; 
`.mariadb` dir is present in /home/dokku, but empty. 

I'm running MariaDB 10.0.19, installed according to [these instructions](https://mariadb.com/kb/en/mariadb/installing-mariadb-deb-files/)

**Comment by remy-actual** [comment]
Solved...
[Events Logger](https://github.com/alessio/dokku-events) plugin was interfering with plugins-install. 
I missed the version restriction >=0.3.13 in the docs. 
Removing it and rerunning plugins-install removed the problem.

**Comment by Zaniyar** [comment]
@remy-actual Can you tell me how you did that? I've the same error with installing mariadb plugin. How did you remove the  20_events plugin?

> 20_events            0.4.0 enabled    dokku core events logging plugin
